import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import cross_val_predict

# ---------------------------------------------------------
# 1. System Setup & Data Loading
# ---------------------------------------------------------
# Define paths based on your project structure
results_dir = Path('Data/Results')
tables_dir = Path('Writing/Tables')
figures_dir = Path('Writing/Figures')

# Ensure output directories exist
tables_dir.mkdir(parents=True, exist_ok=True)
figures_dir.mkdir(parents=True, exist_ok=True)

# Load the raw CSVs generated by your estimation scripts
print("Loading raw evaluation datasets...")
rmse_df = pd.read_csv(results_dir / 'rmse_evaluation_raw.csv')
dml_df = pd.read_csv(results_dir / 'dml_robustness_results.csv')

# ---------------------------------------------------------
# 2. Process and Export RMSE Evaluation Table
# ---------------------------------------------------------
print("Formatting RMSE evaluation table...")

# Set the Model column as the index so pandas can calculate column minimums
rmse_indexed = rmse_df.set_index('Model')

# Find the name of the model with the lowest RMSE for each metric BEFORE rounding
best_models = rmse_indexed.idxmin()

# Round all numeric values to 4 decimal places
rmse_formatted = rmse_indexed.round(4)

# Append the text names as the final row 
# (This will become the final column when we transpose)
rmse_formatted.loc['Best Model'] = best_models

# Transpose the dataframe to match your preferred layout
rmse_transposed = rmse_formatted.T

# Generate the LaTeX string
latex_table_rmse = rmse_transposed.to_latex(
    float_format="%.4f",
    caption="Cross-fitted RMSE for predicting ATE and ATET Nuisance Parameters",
    label="tab:rmse_evaluation",
    column_format="l" + "c" * len(rmse_formatted.index)
)

# Export the final .tex file
with open(tables_dir / 'rmse_evaluation_final.tex', 'w') as f: 
    f.write(latex_table_rmse)

print("Success: rmse_evaluation_final.tex saved.")

# ---------------------------------------------------------
# 3. Process and Export DML Master Table (Panels A, B, C)
# ---------------------------------------------------------
print("Formatting DML Master Causal Table...")

# Select the 4 core models for the narrative and map them to clean column headers
target_models = {
    'OLS - Basic': '(1) OLS Baseline',
    'Boosted Trees': '(2) Boosted Trees',
    'Elastic Net': '(3) Elastic Net',
    'Ensemble (Stacking)': '(4) Ensemble'
}

# Map policy variables to clean row labels
policy_map = {
    'cp_active': 'Congestion Pricing (CP)',
    'lez_active': 'Low Emission Zone (LEZ)',
    'cp_x_lez': 'Synergy (CP $\\times$ LEZ)'
}

# Filter the raw DML dataset
dml_core = dml_df[dml_df['Model'].isin(target_models.keys())].copy()

# Helper function to format coefficients and add significance stars
def format_estimate(coef, pval):
    if pd.isna(coef) or pd.isna(pval):
        return "--" # Handles overlap violations gracefully
    
    stars = ""
    if pval < 0.01:
        stars = "^{***}"
    elif pval < 0.05:
        stars = "^{**}"
    elif pval < 0.10:
        stars = "^{*}"
        
    return f"{coef:.4f}{stars} (p={pval:.3f})"

# Pre-calculate the formatted strings for every estimation type
for prefix in ['PLM_ATE', 'IRM_ATET', 'GATET_Cluster_1', 'GATET_Cluster_0']:
    dml_core[f'{prefix}_fmt'] = dml_core.apply(
        lambda row: format_estimate(row[f'{prefix}_coef'], row[f'{prefix}_pval']), axis=1
    )

master_table_rows = []

# --- PANEL A: PLM ---
master_table_rows.append({'Policy': '\\textbf{Panel A: PLM (Global Average Effect)}', **{v: '' for v in target_models.values()}})
for pol, clean_name in policy_map.items():
    row = {'Policy': f"\\hspace{{4mm}} {clean_name}"}
    for mod, col in target_models.items():
        val = dml_core[(dml_core['Model'] == mod) & (dml_core['Policy'] == pol)]['PLM_ATE_fmt'].values
        row[col] = val[0] if len(val) > 0 else "--"
    master_table_rows.append(row)

master_table_rows.append({'Policy': '', **{v: '' for v in target_models.values()}}) # Spacer

# --- PANEL B: IRM ATET ---
master_table_rows.append({'Policy': '\\textbf{Panel B: IRM ATET (Efficacy for Adopters)}', **{v: '' for v in target_models.values()}})
for pol, clean_name in policy_map.items():
    row = {'Policy': f"\\hspace{{4mm}} {clean_name}"}
    for mod, col in target_models.items():
        val = dml_core[(dml_core['Model'] == mod) & (dml_core['Policy'] == pol)]['IRM_ATET_fmt'].values
        row[col] = val[0] if len(val) > 0 else "--"
    master_table_rows.append(row)

master_table_rows.append({'Policy': '', **{v: '' for v in target_models.values()}}) # Spacer

# --- PANEL C: IRM GATET ---
master_table_rows.append({'Policy': '\\textbf{Panel C: IRM GATET (Heterogeneity by City Type)}', **{v: '' for v in target_models.values()}})
master_table_rows.append({'Policy': '\\textit{Cluster 1: Dense Metropolis}', **{v: '' for v in target_models.values()}})
for pol, clean_name in policy_map.items():
    row = {'Policy': f"\\hspace{{4mm}} {clean_name}"}
    for mod, col in target_models.items():
        val = dml_core[(dml_core['Model'] == mod) & (dml_core['Policy'] == pol)]['GATET_Cluster_1_fmt'].values
        row[col] = val[0] if len(val) > 0 else "--"
    master_table_rows.append(row)

master_table_rows.append({'Policy': '\\textit{Cluster 0: Sprawling Cities}', **{v: '' for v in target_models.values()}})
for pol, clean_name in policy_map.items():
    row = {'Policy': f"\\hspace{{4mm}} {clean_name}"}
    for mod, col in target_models.items():
        val = dml_core[(dml_core['Model'] == mod) & (dml_core['Policy'] == pol)]['GATET_Cluster_0_fmt'].values
        row[col] = val[0] if len(val) > 0 else "--"
    master_table_rows.append(row)

# Convert to DataFrame
final_dml_df = pd.DataFrame(master_table_rows)

# Generate the LaTeX string (escape=False is required to render the \textbf and \hspace commands)
latex_table_dml = final_dml_df.to_latex(
    index=False,
    escape=False,
    column_format="l" + "c" * len(target_models),
    caption="Double Machine Learning Estimates of Urban Climate Policies",
    label="tab:dml_master_results"
)

# Export the final .tex file
with open(tables_dir / 'dml_master_results.tex', 'w') as f:
    # Add a footnote block to the bottom of the table explaining the stars
    f.write(latex_table_dml)
    f.write("\\raggedright \\footnotesize \\textit{Notes:} $p$-values in parentheses. $^{*}$ $p < 0.10$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. 'Failed' estimation bounds denote overlap violations.\n")

print("Success: dml_master_results.tex saved.")

# Set academic plotting style (clean, white background, no grid clutter)
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams.update({'font.size': 12, 'font.family': 'serif'})

# ---------------------------------------------------------
# 4. Figure 1: Coefficient Forest Plot (IRM ATET)
# ---------------------------------------------------------
print("Generating Figure 1: Coefficient Forest Plot...")

# Back out Standard Errors from p-values for the error bars
def approx_se(coef, pval):
    if pd.isna(coef) or pd.isna(pval): 
        return 0
    p = max(pval, 1e-15) # Prevent division by zero for p=0.0
    z = np.abs(norm.ppf(p / 2))
    return abs(coef) / z

dml_core['IRM_ATET_se'] = dml_core.apply(lambda row: approx_se(row['IRM_ATET_coef'], row['IRM_ATET_pval']), axis=1)

# Set up the plot
fig, ax = plt.subplots(figsize=(10, 6))

# Map policies to clean names for the y-axis
y_labels = [policy_map[p] for p in core_policies]
y_ticks = np.arange(len(y_labels))

# Plot each model slightly offset so the error bars don't overlap
offsets = {'(1) OLS Baseline': -0.2, '(2) Boosted Trees': -0.07, '(3) Elastic Net': 0.07, '(4) Ensemble': 0.2}
colors = {'(1) OLS Baseline': 'gray', '(2) Boosted Trees': '#d95f02', '(3) Elastic Net': '#1b9e77', '(4) Ensemble': '#7570b3'}

for mod, clean_mod in target_models.items():
    subset = dml_core[dml_core['Model'] == mod].set_index('Policy').reindex(core_policies)
    y_pos = y_ticks + offsets[clean_mod]
    
    ax.errorbar(subset['IRM_ATET_coef'], y_pos, xerr=subset['IRM_ATET_se'] * 1.96, 
                fmt='o', label=clean_mod, color=colors[clean_mod], 
                capsize=4, elinewidth=2, markersize=8)

ax.axvline(0, color='black', linestyle='--', linewidth=1)
ax.set_yticks(y_ticks)
ax.set_yticklabels(y_labels)
ax.set_xlabel("Average Treatment Effect on the Treated (ATET)\nLog Transport CO2")
ax.set_title("Figure 1: Policy Efficacy by Algorithm (95% CI)", pad=15, fontweight='bold')
ax.legend(title="Algorithm", loc="upper left", bbox_to_anchor=(1, 1))

plt.tight_layout()
fig.savefig(figures_dir / 'forest_plot_atet.pdf', format='pdf', bbox_inches='tight')
plt.close()

# ---------------------------------------------------------
# 5. Figure 2: Heterogeneity Bar Chart (GATET)
# ---------------------------------------------------------
print("Generating Figure 2: Heterogeneity Bar Chart...")

# We will plot the GATET for the Ensemble model
ensemble_df = dml_core[dml_core['Model'] == 'Ensemble (Stacking)'].set_index('Policy').reindex(core_policies)

fig, ax = plt.subplots(figsize=(8, 5))

bar_width = 0.35
x = np.arange(len(core_policies))

# Cluster 0 (Sprawling) and Cluster 1 (Dense)
ax.bar(x - bar_width/2, ensemble_df['GATET_Cluster_0_coef'], bar_width, 
       label='Cluster 0 (Sprawling)', color='#a6cee3', edgecolor='black')
ax.bar(x + bar_width/2, ensemble_df['GATET_Cluster_1_coef'], bar_width, 
       label='Cluster 1 (Dense Metropolis)', color='#1f78b4', edgecolor='black')

ax.axhline(0, color='black', linewidth=1)
ax.set_xticks(x)
ax.set_xticklabels(y_labels)
ax.set_ylabel("Group Average Treatment Effect (GATET)")
ax.set_title("Figure 2: Urban Heterogeneity in Policy Impact (Ensemble)", pad=15, fontweight='bold')
ax.legend()

plt.tight_layout()
fig.savefig(figures_dir / 'heterogeneity_bar_gatet.pdf', format='pdf')
plt.close()

# ---------------------------------------------------------
# 6. Figure 3: Common Support (Overlap) Density Plot
# ---------------------------------------------------------
print("Generating Figure 3: Common Support Density Plot...")
# A quick pass to get propensity scores without re-running the full DML loop
# We use the Elastic Net classifier since it is fast and performed well

# 1. Load data
df = pd.read_csv('Data/urban_emissions_panel_cleaned.csv')
exclude_from_X = ['city_id', 'year', 'log_transport_co2', 'log_total_co2', 'cp_active', 'lez_active', 'cp_impl_year', 'lez_impl_year', 'cp_announce_year', 'lez_announce_year', 'country_id', 'cp_x_lez']
numeric_df = df.select_dtypes(include=[np.number])
X_cols = [col for col in numeric_df.columns if col not in exclude_from_X]
X = df[X_cols]
D = df['cp_active'] # Plotting overlap for Congestion Pricing as the example

# 2. Fast Propensity Score Estimation
clf = make_pipeline(StandardScaler(), LogisticRegressionCV(cv=3, l1_ratios=[0.5], solver='saga', random_state=42, n_jobs=5))
propensity_scores = cross_val_predict(clf, X, D, cv=5, method='predict_proba')[:, 1]

# 3. Plot Density
fig, ax = plt.subplots(figsize=(8, 5))

sns.kdeplot(propensity_scores[D == 1], fill=True, label="Treated (CP Active)", color="#d95f02", ax=ax, alpha=0.5)
sns.kdeplot(propensity_scores[D == 0], fill=True, label="Untreated (No CP)", color="#7570b3", ax=ax, alpha=0.5)

ax.set_xlim(0, 1)
ax.set_xlabel("Estimated Propensity Score $\\hat{P}(D=1|X)$")
ax.set_ylabel("Density")
ax.set_title("Figure 3: Common Support for Congestion Pricing", pad=15, fontweight='bold')
ax.legend()

plt.tight_layout()
fig.savefig(figures_dir / 'overlap_density.pdf', format='pdf')
plt.close()

print(f"Success: All figures generated and saved as PDFs in {figures_dir}")